language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

install: 
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-3.9.1-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-3.9.1-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -p /home/travis/envs/test-environment -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - export HDF5_DIR=/home/travis/envs/test-environment
  - conda install hdf5
  - pip install -r requirements.txt

script:  
  - ./test.sh 
after_script:
  - COVERALLS_REPO_TOKEN=dYV7pqZBuQAUszyONWnINMoo54KZbEFNI coveralls
notifications:
  email:
    on_success: change
    on_failure: always
