language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install: 
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - export HDF5_DIR=/home/travis/miniconda/
  - conda install --yes hdf5
script:  
  - ./test.sh 
after_script:
  - COVERALLS_REPO_TOKEN=dYV7pqZBuQAUszyONWnINMoo54KZbEFNI coveralls
notifications:
  email:
    on_success: change
    on_failure: always
